<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.gluonhq.jfxapps</groupId>
	<artifactId>jfxapps.app.devtools</artifactId>
	<version>${devtools.version}</version>
	<packaging>pom</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<jfxapps.version>1.0.0-SNAPSHOT</jfxapps.version>
		<devtools.version>1.0.0-SNAPSHOT</devtools.version>
		<maven.compiler.plugin.version>3.14.0</maven.compiler.plugin.version>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<flatten-maven-plugin.version>1.7.4-SNAPSHOT</flatten-maven-plugin.version>
	</properties>

	<modules>
		<module>devtools.api</module>
		<module>devtools.app</module>
		<module>devtools.css</module>
		<module>devtools.model</module>
		<module>devtools.i18n</module>
		<module>devtools.startup</module>
		<module>devtools.cmpcheck</module>
		<module>devtools.registry</module>
		<module>devtools.openapi</module>
		<module>devtools.jpms</module>
		<module>devtools.db</module>
		<module>devtools.projects</module> <!-- -->
		<module>devtools.starter</module>
		<!--<module>devtools.metadata</module>-->
	</modules>

	<build>
		<plugins>
			<plugin>
				<!--
                This plugin has 2 internal usages:
                - generate a flattened version of the pom.xml in the repository, maven actions
                will use the flattened pom.xml as the effective pom reducing the
                number of roundtrip during dependency resolution and download
                - manage a centralize version for the project
                -->
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>${flatten-maven-plugin.version}</version>
				<configuration>
					<flattenDependencyMode>all</flattenDependencyMode>
					<flattenMode>bom</flattenMode> <!-- Resolve properties like
					${jfxapps.version} -->
					<!--<updatePomFile>true</updatePomFile>   Ensures the POM file is updated -->
				</configuration>
				<executions>
					<!-- enable flattening -->
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<!-- ensure proper cleanup -->
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- slow the build , so commented (at least for now)-->
			<!--
			<plugin>
				<groupId>io.github.git-commit-id</groupId>
			    <artifactId>git-commit-id-maven-plugin</artifactId>
			</plugin>
			-->
		</plugins>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.api</artifactId>
				<version>${devtools.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.metadata.customization</artifactId>
				<version>${devtools.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.metadata.model</artifactId>
				<version>${devtools.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.metadata.modeldata</artifactId>
				<version>${devtools.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.model</artifactId>
				<version>${devtools.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>devtools.starter</artifactId>
				<version>${devtools.version}</version>
			</dependency>

			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps.core.api</artifactId>
				<version>${jfxapps.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps.core.starter</artifactId>
				<version>${jfxapps.version}</version>
			</dependency>
			<dependency>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps.core.starter.test</artifactId>
				<version>${jfxapps.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>