<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.treilhes.scenebuilder</groupId>
    <artifactId>scenebuilder-parent</artifactId>
    <packaging>pom</packaging>
    <version>${scenebuilder.version}</version>
    <name>Scene Builder</name>
    <description>Scene Builder is a visual, drag n drop, layout tool for
        designing JavaFX application user interfaces</description>
    <inceptionYear>2012</inceptionYear>
    <url>https://github.com/gluonhq/scenebuilder</url>

    <modules>
        <!--<module>fxml.serializer</module>-->
        <module>scenebuilder.core</module>
        <module>scenebuilder.registry</module>
        <module>scenebuilder.launcher</module>
        <module>scenebuilder.fxom</module>
        <!--
        <module>scenebuilder.ext</module>
        <module>scenebuilder.gluon</module>
        -->
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>25</java.version>
        <!-- exporting a package from system module java.base is not allowed
        with release -->
        <!--<maven.compiler.release>24</maven.compiler.release>-->
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <scenebuilder.version>25.0.0-SNAPSHOT</scenebuilder.version>
        <emc4j.version>1.0.0-SNAPSHOT</emc4j.version>
        <jfxplace.version>1.0.0-SNAPSHOT</jfxplace.version>
        

        <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
        <maven-dependency-plugin.version>3.6.1</maven-dependency-plugin.version>
        <maven-failsafe-plugin.version>3.5.4</maven-failsafe-plugin.version>
        <maven-surefire-plugin.version>${maven-failsafe-plugin.version}</maven-surefire-plugin.version>
        <maven-clean-plugin.version>3.0.0</maven-clean-plugin.version>
        <maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
        <maven-invoker-plugin.version>3.8.0</maven-invoker-plugin.version>
        <versions-maven-plugin.version>2.9.0</versions-maven-plugin.version>
        <maven-project-info-reports-plugin.version>2.6</maven-project-info-reports-plugin.version>
        <maven-checkstyle-plugin.version>3.5.0</maven-checkstyle-plugin.version>
        <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>
        <maven-javadoc-plugin.version>3.12.0</maven-javadoc-plugin.version>
        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <jacoco-maven-plugin.version>0.8.14</jacoco-maven-plugin.version>
        
        <flatten-maven-plugin.version>1.7.4-SNAPSHOT</flatten-maven-plugin.version>
        

        <spring.boot.version>4.0.0-RC2</spring.boot.version>
        <org.mapstruct.version>1.6.3</org.mapstruct.version>
        <rxjavafx.version>3.0.2</rxjavafx.version>
        <ikonli.version>12.3.1</ikonli.version>
        
        <!-- internal -->
        <sonar.projectKey>jfxapps_scenebuilder_aa4527b4-a246-4f94-a740-37433a483f61</sonar.projectKey>
        <sonar.projectName>scenebuilder</sonar.projectName>
        <sonar.qualitygate.wait>true</sonar.qualitygate.wait>
        <sonar.coverage.jacoco.xmlReportPaths>**/target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
    </properties>

    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>gluon-nexus</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
        
            <!-- scenebuilder.core -->
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.api</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.app</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.starter</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.starter.test</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.drag.and.drop</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.javafx.customization</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.jobs</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.main</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.customization</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx.fx</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx</artifactId>
                <version>${scenebuilder.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx.11</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx.15</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx.21</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.javafx.22</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.metadata.sbjavafx</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.selection</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ui</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <!-- scenebuilder.ext -->
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.library.control</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.controls</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.controls.tooling</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.css.analyser</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.debug.menu</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.document</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.dummy</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.editor.fxml</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.editor.script</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.editors</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.exporter</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.glossary</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.help.features</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.i18n</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.library.image</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.inspector</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.preview</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.script</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.script.graalvm-javascript</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.script.graalvm-javascript-rt</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.source.gen</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.source.view</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.theme</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.templates</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <dependency>
                <groupId>com.treilhes.scenebuilder</groupId>
                <artifactId>scenebuilder.ext.welcome</artifactId>
                <version>${scenebuilder.version}</version>
            </dependency>

            <!-- jfxplace.core -->
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.core.starter</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.core.starter.test</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.javafx.starter</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.core.api</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.core.fxom</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.fxom.api</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.core.metadata</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>

            <!-- jfxapps.metadata -->
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace.fxom.metadata.generator</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>
            <dependency>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace-fxom-metadata-maven-plugin</artifactId>
                <version>${jfxplace.version}</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.mapstruct/mapstruct -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.pdfsam.rxjava3/rxjavafx -->
            <dependency>
                <groupId>org.pdfsam.rxjava3</groupId>
                <artifactId>rxjavafx</artifactId>
                <version>${rxjavafx.version}</version>
            </dependency>

            <dependency>
                <groupId>org.kordamp.ikonli</groupId>
                <artifactId>ikonli-javafx</artifactId>
                <version>${ikonli.version}</version>
            </dependency>
            <dependency>
                <groupId>org.kordamp.ikonli</groupId>
                <artifactId>ikonli-fontawesome5-pack</artifactId>
                <version>${ikonli.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>delivery</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-javadoc</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <configuration>
                                    <!-- FIXME allow missing javadoc comments, TEMPORARY-->
                                    <failOnError>false</failOnError>
                                    <additionalOptions>
                                        <option>--add-exports</option>
                                        <option>
                                            javafx.graphics/com.sun.javafx.scene=scenebuilder.core</option>
                                        <option>--add-exports</option>
                                        <option>
                                            javafx.graphics/com.sun.javafx.geometry=scenebuilder.core</option>
                                        <option>--add-exports</option>
                                        <option>
                                            javafx.graphics/com.sun.javafx.scene=scenebuilder.ext.css.analyser</option>
                                    </additionalOptions>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>prepare-agent-integration</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>prepare-agent-integration</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>report</id>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- Windows profile -->
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <properties>
                <glass.platform>Win</glass.platform>
                <awt.headless>false</awt.headless>
            </properties>
        </profile>

        <!-- macOS profile -->
        <profile>
            <id>macos</id>
            <activation>
                <os>
                    <family>Mac</family>
                </os>
            </activation>
            <properties>
                <glass.platform>Mac</glass.platform>
                <awt.headless>false</awt.headless>
            </properties>
        </profile>

        <!-- Linux profile -->
        <profile>
            <id>linux</id>
            <activation>
                <os>
                    <family>Unix</family>
                </os>
            </activation>
            <properties>
                <glass.platform>Gtk</glass.platform>
                <awt.headless>false</awt.headless>
            </properties>
        </profile>
        <profile>
            <id>headless</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <glass.platform>Headless</glass.platform>
                <awt.headless>true</awt.headless>
            </properties>
        </profile>
    </profiles>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <!--
                    This plugin has 2 internal usages:
                    - generate a flattened version of the pom.xml in the repository, maven actions
                    will use the flattened pom.xml as the effective pom reducing the
                    number of roundtrip during dependency resolution and download
                    - manage a centralize version for the project
                    -->
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${flatten-maven-plugin.version}</version>
                    <configuration>
                        <flattenDependencyMode>direct</flattenDependencyMode>
                        <flattenMode>bom</flattenMode> <!-- Resolve properties like
                        ${scenebuilder.version} -->
                        <!--<updatePomFile>true</updatePomFile>   Ensures the POM file is updated -->
                    </configuration>
                    <executions>
                        <!-- enable flattening -->
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <!-- ensure proper cleanup -->
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.treilhes.emc4j</groupId>
                    <artifactId>emc4j-registry-maven-plugin</artifactId>
                    <version>${emc4j.version}</version>
                </plugin>
                <plugin>
                    <groupId>com.treilhes.emc4j</groupId>
                    <artifactId>emc4j-dependency-plugin</artifactId>
                    <version>${emc4j.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                </plugin>
                <!-- Build KIT wherever parent is cleaned -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <compilerArgs>

                            <arg>--add-exports</arg>
                            <arg>
                                spring.core/org.springframework.core.patch=emc4j.boot.layer</arg>
                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.geometry=jfxplace.core.api</arg>
                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.scene=jfxplace.core.api</arg>
                            <arg>--add-exports</arg>
                            <arg>
                                javafx.fxml/com.sun.javafx.fxml=jfxplace.core.fxom</arg>
                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.geometry=scenebuilder.core.fxom</arg>

                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.scene=scenebuilder.core.fxom</arg>
                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.scene=scenebuilder.fxml.api</arg>

                            <arg>--add-exports</arg>
                            <arg>
                                javafx.graphics/com.sun.javafx.scene=scenebuilder.ext.css.analyser</arg>
                        </compilerArgs>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${org.mapstruct.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                    <executions>
                        <execution>
                            <id>test</id>
                            <phase>test-compile</phase>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                            <configuration>
                                <compilerArgs>
                                    <arg>--add-exports</arg>
                                    <arg>
                                        javafx.graphics/com.sun.javafx.application=ALL-UNNAMED</arg>
                                    <arg>--add-exports</arg>
                                    <arg>
                                        javafx.base/com.sun.javafx.beans=spring.core</arg>
                                </compilerArgs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <!--
                https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>


                <!-- Deploy to Maven Central -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.0.0-M1</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                    <inherited>false</inherited>
                </plugin>

                <!-- Testing -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <systemPropertyVariables>
                            <maven.version>${maven.version}</maven.version>
                            <maven.home>${maven.home}</maven.home>
                            <java.awt.headless>${awt.headless}</java.awt.headless>
                            <glass.platform>${glass.platform}</glass.platform>
                            <javafx.allowjs>true</javafx.allowjs>
                        </systemPropertyVariables>
                        <useModulePath>false</useModulePath>
                        <jvm>${java.home}/bin/java</jvm>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven-failsafe-plugin.version}</version>
                    <configuration>
                        <systemPropertyVariables>
                            <maven.version>${maven.version}</maven.version>
                            <maven.home>${maven.home}</maven.home>
                            <java.awt.headless>${awt.headless}</java.awt.headless>
                            <glass.platform>${glass.platform}</glass.platform>
                            <javafx.allowjs>true</javafx.allowjs>
                        </systemPropertyVariables>
                        <jvm>${java.home}/bin/java</jvm>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <!-- <version>3.3.0</version> -->
                    <version>3.3.1-SNAPSHOT</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-invoker-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <javaHome>${java.home}</javaHome>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>2.9.0</version>
                    <executions>
                        <execution>
                            <id>generate-debt-report</id>
                            <goals>
                                <goal>dependency-updates-report</goal>
                            </goals>
                            <phase>prepare-package</phase>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${maven-checkstyle-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>${maven-project-info-reports-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>io.github.git-commit-id</groupId>
                    <artifactId>git-commit-id-maven-plugin</artifactId>
                    <version>9.0.1</version>
                    <executions>
                        <execution>
                            <id>get-git-infos</id>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
                        <generateGitPropertiesFilename>
                            ${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                        <commitIdGenerationMode>full</commitIdGenerationMode>
                        <offline>true</offline>
                        <failOnNoGitDirectory>false</failOnNoGitDirectory>
                        <skipPoms>false</skipPoms>
                        <excludeProperties>
                            <excludeProperty>git.build.user.email</excludeProperty>
                            <excludeProperty>git.build.user.name</excludeProperty>
                            <excludeProperty>git.commit.user.email</excludeProperty>
                            <excludeProperty>git.commit.user.name</excludeProperty>
                        </excludeProperties>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.treilhes.jfxplace</groupId>
                                        <artifactId>jfxplace-source-override-maven-plugin</artifactId>
                                        <versionRange>[0.0.0,)</versionRange>
                                        <goals>
                                            <goal>override</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore/>
                                    </action>
                                </pluginExecution>
                                
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.treilhes.emc4j</groupId>
                                        <artifactId>emc4j-dependency-plugin</artifactId>
                                        <versionRange>[0.0.0,)</versionRange>
                                        <goals>
                                            <goal>properties</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <execute>
                                            <runOnConfiguration>true</runOnConfiguration>
                                        </execute>
                                    </action>
                                </pluginExecution>
                                
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-dependency-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>properties</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <execute>
                                            <runOnConfiguration>true</runOnConfiguration>
                                        </execute>
                                    </action>
                                </pluginExecution>

                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.codehaus.mojo</groupId>
                                        <artifactId>flatten-maven-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>flatten</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>

                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-jar-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>jar</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>

                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-invoker-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>run</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>

                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.treilhes.jfxplace</groupId>
                                        <artifactId>jfxplace-fxom-metadata-maven-plugin</artifactId>
                                        <versionRange>[0.0.0,)</versionRange>
                                        <goals>
                                            <goal>metadataSource</goal>
                                            <goal>metadataResource</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>com.treilhes.emc4j</groupId>
                                        <artifactId>emc4j-registry-maven-plugin</artifactId>
                                        <versionRange>[0.0.0,)</versionRange>
                                        <goals>
                                            <goal>jfxappsRegistry</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-plugin-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>descriptor</goal>
                                            <goal>helpmojo</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <execute />
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <organization>
        <name>Gluon</name>
        <url>https://www.gluonhq.com</url>
    </organization>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/gluonhq/ChatApp/issues</url>
    </issueManagement>

    <licenses>
        <license>
            <name>BSD 3-Clause</name>
            <url>https://opensource.org/licenses/BSD-3-Clause</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Abhinay Agarwal</name>
            <email>abhinay.agarwal@gluonhq.com</email>
            <organization>Gluon</organization>
            <organizationUrl>https://www.gluonhq.com</organizationUrl>
        </developer>
        <developer>
            <name>Joeri Sykora</name>
            <email>joeri.sykora@gluonhq.com</email>
            <organization>Gluon</organization>
            <organizationUrl>https://www.gluonhq.com</organizationUrl>
        </developer>
        <developer>
            <name>Jos? Pereda</name>
            <email>jose.pereda@gluonhq.com</email>
            <organization>Gluon</organization>
            <organizationUrl>https://www.gluonhq.com</organizationUrl>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/gluonhq/scenebuilder</url>
        <connection>scm:git:git://github.com/gluonhq/scenebuilder.git</connection>
        <developerConnection>
            scm:git:ssh://git@github.com:gluonhq/scenebuilder.git</developerConnection>
    </scm>

    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>
        </plugins>
    </reporting>

</project>