jfxapps:
  platform:
    rootPath: ./target/devapp
  registry:
    snapshotsAllowed: true
  repository:
    directory: ${user.home}/.m2/repository
    redirectionsEnabled: false
    redirect:
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.api
        path: ../../jfxapps.core/jfxapps.core.api/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.appmngr
        path: ../../jfxapps.core/jfxapps.core.appmngr/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.ui
        path: ../../jfxapps.core/jfxapps.core.ui/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.jobs
        path: ../../jfxapps.core/jfxapps.core.jobs/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.filesystem
        path: ../../jfxapps.core/jfxapps.core.filesystem/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.menu
        path: ../../jfxapps.core/jfxapps.core.menu/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.preferences
        path: ../../jfxapps.core/jfxapps.core.preferences/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.core.utils
        path: ../../jfxapps.core/jfxapps.core.utils/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.ext.about
        path: ../../jfxapps.ext/jfxapps.ext.about/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: jfxapps.ext.scenicview
        path: ../../jfxapps.ext/jfxapps.ext.scenicview/target/classes

      - groupId: com.gluonhq.jfxapps
        artifactId: manager.api
        path: ../../jfxapps.app/jfxapps.app.manager/manager.api/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: manager.app
        path: ../../jfxapps.app/jfxapps.app.manager/manager.app/target/classes

      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.api
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.api/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.app
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.app/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.i18n
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.i18n/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.startup
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.startup/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.cmpcheck
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.cmpcheck/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.openapi
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.openapi/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: devtools.db
        path: ../../jfxapps.app/jfxapps.app.devtools/devtools.db/target/classes

      - groupId: com.gluonhq.jfxapps
        artifactId: scenebuilder.api
        path: ../../jfxapps.app/jfxapps.app.scenebuilder/scenebuilder.core/scenebuilder.api/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: scenebuilder.app
        path: ../../jfxapps.app/jfxapps.app.scenebuilder/scenebuilder.core/scenebuilder.app/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: scenebuilder.ui
        path: ../../jfxapps.app/jfxapps.app.scenebuilder/scenebuilder.core/scenebuilder.ui/target/classes
      - groupId: com.gluonhq.jfxapps
        artifactId: scenebuilder.selection
        path: ../../jfxapps.app/jfxapps.app.scenebuilder/scenebuilder.core/scenebuilder.selection/target/classes

      - groupId: com.gluonhq.jfxapps
        artifactId: scenebuilder.ext.menu
        path: ../../jfxapps.app/jfxapps.app.scenebuilder/scenebuilder.ext/scenebuilder.ext.menu/target/classes

server:
  port: 8080
  tomcat:
    basedir: ./target
    threads:
      max: 5
      min-spare: 2
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b'
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:file:./target/jfxapps-h2-db

springdoc:
  show-actuator: true