<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.gluonhq.jfxapps</groupId>
    <artifactId>jfxapps.app.sample</artifactId>
    <version>${sample.version}</version>
  </parent>
  <artifactId>jfxapps.app.sample.registry</artifactId>
  
  
	<build>
		<plugins>
			<plugin>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps-registry-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate-registry-resources</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>jfxappsRegistry</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<format>json</format>
					<registry>
						<uuid>7dcf6a61-0c83-4f9f-8c04-c17e7af81095</uuid>
						<description>
							<image>ScenebuilderSplash_400x400.png</image>
							<title>Sample Application Registry</title>
							<text>Sample Application Registry to show some things</text>
						</description>
						<applications>
							<application>
								<uuid>99982f35-4fe7-4eb7-b8df-fc4ed034a6d9</uuid>
								<splash>ScenebuilderSplash_400x400.png</splash>
								<dependency>
									<groupId>com.gluonhq.jfxapps</groupId>
									<artifactId>sample.app</artifactId>
									<version>${sample.version}</version>
								</dependency>
								<description>
									<image>ScenebuilderSplash_400x400.png</image>
									<title>Sample Application</title>
									<text>Sample Application Registry to show some things</text>
								</description>
							</application>
						</applications>
					</registry>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>