<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gluonhq.jfxapps</groupId>
		<artifactId>jfxapps.app.devtools</artifactId>
		<version>${devtools.version}</version>
	</parent>
	<artifactId>devtools.registry</artifactId>

	<build>
		<plugins>
			<plugin>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps-registry-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate-registry-resources</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>jfxappsRegistry</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<format>json</format>
					<registry>
						<uuid>f2b3395a-70a1-48d9-ba12-a20d6c9f4940</uuid>
						<applications>
							<application>
								<uuid>1b8bb5f3-efb3-41a6-b6f0-12c9d96fc6a2</uuid>
								<dependency>
									<groupId>com.gluonhq.jfxapps</groupId>
									<artifactId>devtools.api</artifactId>
									<version>${devtools.version}</version>
								</dependency>
								<description>
									<icon>fxmlRunner64x64.png</icon>
									<title>FXML Runner</title>
									<text>App that run fxml files</text>
								</description>
								<extensions>
									<extension>
										<uuid>
											deabfbdf-0889-4723-9417-77450b962742</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.app</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
									<extension>
										<uuid>
											733baa71-86ee-42db-b2d5-3f8111138de4</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.i18n</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
									<extension>
										<uuid>
											5b660c25-a77a-4435-b2ca-20ac2c734303</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.startup</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
									<extension>
										<uuid>
											d474380c-8b2a-41ff-ab49-93aee05160ff</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.cmpcheck</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
									<extension>
										<uuid>
											b1df62f8-42bd-45e2-bdbb-434ef2b0e4c2</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.openapi</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
									<extension>
										<uuid>
											5aadfc19-93f1-4d0b-b21a-c5d7ad5a2b05</uuid>
										<dependency>
											<groupId>com.gluonhq.jfxapps</groupId>
											<artifactId>devtools.db</artifactId>
											<version>${devtools.version}</version>
										</dependency>
									</extension>
								</extensions>
							</application>
						</applications>
					</registry>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>