<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gluonhq.jfxapps</groupId>
        <artifactId>jfxapps.boot</artifactId>
        <version>${jfxapps.version}</version>
    </parent>
    <artifactId>jfxapps.boot.maven</artifactId>

    

    <dependencies>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>jfxapps.boot.api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>jfxapps.boot.platform</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>jfxapps.boot.starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>jfxapps.boot.starter.test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
    	
    	<plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useModulePath>false</useModulePath>
                    <argLine>
                        --patch-module
                        maven.model=${org.apache.maven:maven-model-builder:jar}
                    </argLine>
                </configuration>
            </plugin>
    	</plugins>
    </build>
</project>