<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gluonhq.jfxapps</groupId>
		<artifactId>jfxapps.app</artifactId>
		<version>${jfxapps.version}</version>
	</parent>
	<artifactId>jfxapps.app.registry.mandatory</artifactId>
	
	<properties>
		<devtools.version>1.0.0-SNAPSHOT</devtools.version>
	</properties>
	
	<build>
		<plugins>
			<plugin>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>jfxapps-registry-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate-registry-resources</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>jfxappsRegistry</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<format>json</format>
					<registry>
						<uuid>6180b14e-4d4b-47c6-9288-72d86cde3b85</uuid>
						<description>
							<image>jfxapps_apps_256x256.png</image>
							<title>JfxApps applications and plugins Registry</title>
							<text>Contains all applications and plugins
								mandotory for running</text>
						</description>
						<registries>
							<registry>
								<dependency>
									<groupId>com.gluonhq.jfxapps</groupId>
									<artifactId>manager.registry</artifactId>
									<version>${manager.version}</version>
								</dependency>
							</registry>
							<registry>
								<dependency>
									<groupId>com.gluonhq.jfxapps</groupId>
									<artifactId>devtools.registry</artifactId>
									<version>${devtools.version}</version>
								</dependency>
							</registry>
							<registry>
								<dependency>
									<groupId>com.gluonhq.jfxapps</groupId>
									<artifactId>scenebuilder.registry</artifactId>
									<version>${scenebuilder.version}</version>
								</dependency>
							</registry>
						</registries>
					</registry>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>