<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.gluonhq.jfxapps</groupId>
    <artifactId>scenebuilder.driver</artifactId>
    <version>${scenebuilder.version}</version>
  </parent>
  <artifactId>scenebuilder.driver.javafx</artifactId>
  <packaging>pom</packaging>
  <modules>
      <module>scenebuilder.driver.javafx.common</module>
      <module>scenebuilder.driver.javafx.22</module>
  </modules>
</project>