<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>scenebuilder.ext.css.analyser</artifactId>

    <parent>
        <groupId>com.treilhes.scenebuilder</groupId>
        <artifactId>scenebuilder.ext</artifactId>
        <version>${scenebuilder.version}</version>
    </parent>

    <description>
        Scene Builder CSS Analyser Extension, provide a view that analyses CSS configuration of a document
        and shows the results in a table.
    </description>

    <dependencies>
        <dependency>
            <groupId>com.treilhes.scenebuilder</groupId>
            <artifactId>scenebuilder.api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.treilhes.scenebuilder</groupId>
            <artifactId>scenebuilder.starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.treilhes.scenebuilder</groupId>
            <artifactId>scenebuilder.starter.test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace-helper-plugin</artifactId>
                <executions>
                    <execution>
                        <id>argLine</id>
                        <goals>
                            <goal>argline</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useModulePath>true</useModulePath>
                    <argLine>
                        ${jfxplaceArgLine}
                        --add-opens javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
                        --add-opens javafx.graphics/com.sun.javafx.scene=scenebuilder.ext.css.analyser
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>