<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>it.boot.loader</groupId>
    <artifactId>common-loader</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>root</module>
        <module>root-ext1</module>
        <module>root-ext1-ext1</module>
        <module>app1</module>
        <module>app1-ext1</module>
        <module>app1-ext1-ext1</module>
    </modules>

	<properties>
        <jfxapps.version>${parent.jfxapps.version}</jfxapps.version>
        <!-- compiler -->
        <maven.compiler.plugin.version>${parent.maven.compiler.plugin.version}</maven.compiler.plugin.version>
        <maven.compiler.release>${parent.maven.compiler.source}</maven.compiler.release>
        <maven.compiler.source>${parent.maven.compiler.source}</maven.compiler.source>
        <maven.compiler.target>${parent.maven.compiler.target}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
	
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.gluonhq.jfxapps</groupId>
                <artifactId>parent</artifactId>
                <version>${jfxapps.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>