/*
 * Copyright (c) 2016, 2021, Gluon and/or its affiliates.
 * Copyright (c) 2012, 2014, Oracle and/or its affiliates.
 * All rights reserved. Use is subject to license terms.
 *
 * This file is available and licensed under the following license:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  - Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the distribution.
 *  - Neither the name of Oracle Corporation and Gluon nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.oracle.javafx.scenebuilder.core.metadata;

import com.oracle.javafx.scenebuilder.core.metadata.util.PropertyName;

public interface PropertyNames {


    // Property Names
    public final PropertyName absoluteName =  new PropertyName("absolute"); //NOCHECK
    public final PropertyName acceleratorName =  new PropertyName("accelerator"); //NOCHECK
    public final PropertyName accessibleHelpName =  new PropertyName("accessibleHelp"); //NOCHECK
    public final PropertyName accessibleRoleName =  new PropertyName("accessibleRole"); //NOCHECK
    public final PropertyName accessibleRoleDescriptionName =  new PropertyName("accessibleRoleDescription"); //NOCHECK
    public final PropertyName accessibleTextName =  new PropertyName("accessibleText"); //NOCHECK
    public final PropertyName actionItemsName = new PropertyName("actionItems"); //NOCHECK
    public final PropertyName alignmentName = new PropertyName("alignment"); //NOCHECK
    public final PropertyName allowIndeterminateName =  new PropertyName("allowIndeterminate"); //NOCHECK
    public final PropertyName alternativeColumnFillVisibleName =  new PropertyName("alternativeColumnFillVisible"); //NOCHECK
    public final PropertyName alternativeRowFillVisibleName =  new PropertyName("alternativeRowFillVisible"); //NOCHECK
    public final PropertyName alwaysOnTopName = new PropertyName("alwaysOnTop"); //NOCHECK
    public final PropertyName anchorLocationName =  new PropertyName("anchorLocation"); //NOCHECK
    public final PropertyName anchorXName =  new PropertyName("anchorX"); //NOCHECK
    public final PropertyName anchorYName =  new PropertyName("anchorY"); //NOCHECK
    public final PropertyName animatedName =  new PropertyName("animated"); //NOCHECK
    public final PropertyName arcHeightName =  new PropertyName("arcHeight"); //NOCHECK
    public final PropertyName arcWidthName =  new PropertyName("arcWidth"); //NOCHECK
    public final PropertyName autoFixName =  new PropertyName("autoFix"); //NOCHECK
    public final PropertyName autoHideName =  new PropertyName("autoHide"); //NOCHECK
    public final PropertyName autoRangingName =  new PropertyName("autoRanging"); //NOCHECK
    public final PropertyName autoSizeChildrenName =  new PropertyName("autoSizeChildren"); //NOCHECK
    public final PropertyName axisSortingPolicyName =  new PropertyName("axisSortingPolicy"); //NOCHECK
    public final PropertyName barGapName =  new PropertyName("barGap"); //NOCHECK
    public final PropertyName baselineOffsetName =  new PropertyName("baselineOffset"); //NOCHECK
    public final PropertyName blendModeName =  new PropertyName("blendMode"); //NOCHECK
    public final PropertyName blockIncrementName =  new PropertyName("blockIncrement"); //NOCHECK
    public final PropertyName bottomName =  new PropertyName("bottom"); //NOCHECK
    public final PropertyName bottomNavigationTypeName = new PropertyName("type"); //NOCHECK
    public final PropertyName boundsInLocalName = new PropertyName("boundsInLocal"); //NOCHECK
    public final PropertyName boundsInParentName =  new PropertyName("boundsInParent"); //NOCHECK
    public final PropertyName boundsTypeName =  new PropertyName("boundsType"); //NOCHECK
    public final PropertyName buttonCellName =  new PropertyName("buttonCell"); //NOCHECK
    public final PropertyName buttonMinWidthName =  new PropertyName("buttonMinWidth"); //NOCHECK
    public final PropertyName buttonOrderName =  new PropertyName("buttonOrder"); //NOCHECK
    public final PropertyName buttonsName =  new PropertyName("buttons"); //NOCHECK
    public final PropertyName buttonTypesName =  new PropertyName("buttonTypes"); //NOCHECK
    public final PropertyName cacheName =  new PropertyName("cache"); //NOCHECK
    public final PropertyName cacheHintName =  new PropertyName("cacheHint"); //NOCHECK
    public final PropertyName cacheShapeName =  new PropertyName("cacheShape"); //NOCHECK
    public final PropertyName cancelButtonName =  new PropertyName("cancelButton"); //NOCHECK
    public final PropertyName categoriesName = new PropertyName("categories"); //NOCHECK
    public final PropertyName categoryGapName =  new PropertyName("categoryGap"); //NOCHECK
    public final PropertyName categorySpacingName =  new PropertyName("categorySpacing"); //NOCHECK
    public final PropertyName centerName =  new PropertyName("center"); //NOCHECK
    public final PropertyName centerShapeName =  new PropertyName("centerShape"); //NOCHECK
    public final PropertyName centerXName =  new PropertyName("centerX"); //NOCHECK
    public final PropertyName centerYName =  new PropertyName("centerY"); //NOCHECK
    public final PropertyName childrenName =  new PropertyName("children"); //NOCHECK
    public final PropertyName clipName =  new PropertyName("clip"); //NOCHECK
    public final PropertyName clockwiseName =  new PropertyName("clockwise"); //NOCHECK
    public final PropertyName closableName =  new PropertyName("closable"); //NOCHECK
    public final PropertyName collapsedContentName = new PropertyName("collapsedContent"); //NOCHECK
    public final PropertyName collapsibleName = new PropertyName("collapsible"); //NOCHECK
    public final PropertyName colorName =  new PropertyName("color"); //NOCHECK
    public final PropertyName columnConstraintsName =  new PropertyName("columnConstraints"); //NOCHECK
    public final PropertyName columnHalignmentName =  new PropertyName("columnHalignment"); //NOCHECK
    public final PropertyName columnResizePolicyName =  new PropertyName("columnResizePolicy"); //NOCHECK
    public final PropertyName columnsName =  new PropertyName("columns"); //NOCHECK
    public final PropertyName consumeAutoHidingEventsName =  new PropertyName("consumeAutoHidingEvents"); //NOCHECK
    public final PropertyName contentName =  new PropertyName("content"); //NOCHECK
    public final PropertyName contentBiasName =  new PropertyName("contentBias"); //NOCHECK
    public final PropertyName contentDisplayName =  new PropertyName("contentDisplay"); //NOCHECK
    public final PropertyName contentTextName =  new PropertyName("contentText"); //NOCHECK
    public final PropertyName contextMenuName =  new PropertyName("contextMenu"); //NOCHECK
    public final PropertyName contextMenuEnabledName =  new PropertyName("contextMenuEnabled"); //NOCHECK
    public final PropertyName controlXName =  new PropertyName("controlX"); //NOCHECK
    public final PropertyName controlX1Name =  new PropertyName("controlX1"); //NOCHECK
    public final PropertyName controlX2Name =  new PropertyName("controlX2"); //NOCHECK
    public final PropertyName controlYName =  new PropertyName("controlY"); //NOCHECK
    public final PropertyName controlY1Name =  new PropertyName("controlY1"); //NOCHECK
    public final PropertyName controlY2Name =  new PropertyName("controlY2"); //NOCHECK
    public final PropertyName createSymbolsName =  new PropertyName("createSymbols"); //NOCHECK
    public final PropertyName cullFaceName =  new PropertyName("cullFace"); //NOCHECK
    public final PropertyName currentPageIndexName =  new PropertyName("currentPageIndex"); //NOCHECK
    public final PropertyName cursorName =  new PropertyName("cursor"); //NOCHECK
    public final PropertyName defaultButtonName =  new PropertyName("defaultButton"); //NOCHECK
    public final PropertyName depthName =  new PropertyName("depth"); //NOCHECK
    public final PropertyName depthTestName =  new PropertyName("depthTest"); //NOCHECK
    public final PropertyName disableName =  new PropertyName("disable"); //NOCHECK
    public final PropertyName dividerPositionsName =  new PropertyName("dividerPositions"); //NOCHECK
    public final PropertyName divisionsName =  new PropertyName("divisions"); //NOCHECK
    public final PropertyName drawModeName =  new PropertyName("drawMode"); //NOCHECK
    public final PropertyName editableName =  new PropertyName("editable"); //NOCHECK
    public final PropertyName effectName =  new PropertyName("effect"); //NOCHECK
    public final PropertyName effectiveNodeOrientationName =  new PropertyName("effectiveNodeOrientation"); //NOCHECK
    public final PropertyName elementsName =  new PropertyName("elements"); //NOCHECK
    public final PropertyName ellipsisStringName =  new PropertyName("ellipsisString"); //NOCHECK
    public final PropertyName endMarginName =  new PropertyName("endMargin"); //NOCHECK
    public final PropertyName endXName =  new PropertyName("endX"); //NOCHECK
    public final PropertyName endYName =  new PropertyName("endY"); //NOCHECK
    public final PropertyName expandableContentName =  new PropertyName("expandableContent"); //NOCHECK
    public final PropertyName expandedContentName = new PropertyName("expandedContent"); //NOCHECK
    public final PropertyName expandedName = new PropertyName("expanded"); //NOCHECK
    public final PropertyName expandedItemCountName =  new PropertyName("expandedItemCount"); //NOCHECK
    public final PropertyName expandedPropertyName = new PropertyName("expanded"); //NOCHECK
    public final PropertyName farClipName = new PropertyName("farClip"); //NOCHECK
    public final PropertyName fieldOfViewName =  new PropertyName("fieldOfView"); //NOCHECK
    public final PropertyName fillName =  new PropertyName("fill"); //NOCHECK
    public final PropertyName fillHeightName =  new PropertyName("fillHeight"); //NOCHECK
    public final PropertyName fillRuleName =  new PropertyName("fillRule"); //NOCHECK
    public final PropertyName fillWidthName =  new PropertyName("fillWidth"); //NOCHECK
    public final PropertyName fitHeightName =  new PropertyName("fitHeight"); //NOCHECK
    public final PropertyName fitToHeightName =  new PropertyName("fitToHeight"); //NOCHECK
    public final PropertyName fitToWidthName =  new PropertyName("fitToWidth"); //NOCHECK
    public final PropertyName fitWidthName =  new PropertyName("fitWidth"); //NOCHECK
    public final PropertyName fixedCellSizeName =  new PropertyName("fixedCellSize"); //NOCHECK
    public final PropertyName fixedEyeAtCameraZeroName =  new PropertyName("fixedEyeAtCameraZero"); //NOCHECK
    public final PropertyName focusTraversableName =  new PropertyName("focusTraversable"); //NOCHECK
    public final PropertyName fontName =  new PropertyName("font"); //NOCHECK
    public final PropertyName fontScaleName =  new PropertyName("fontScale"); //NOCHECK
    public final PropertyName fontSmoothingTypeName =  new PropertyName("fontSmoothingType"); //NOCHECK
    public final PropertyName forceZeroInRangeName =  new PropertyName("forceZeroInRange"); //NOCHECK
    public final PropertyName fullScreenName = new PropertyName("fullScreen"); //NOCHECK
    public final PropertyName fullScreenExitHintName = new PropertyName("fullScreenExitHint"); //NOCHECK
    public final PropertyName gapStartAndEndName =  new PropertyName("gapStartAndEnd"); //NOCHECK
    public final PropertyName graphicName =  new PropertyName("graphic"); //NOCHECK
    public final PropertyName graphicTextGapName =  new PropertyName("graphicTextGap"); //NOCHECK
    public final PropertyName gridLinesVisibleName =  new PropertyName("gridLinesVisible"); //NOCHECK
    public final PropertyName halignmentName =  new PropertyName("halignment"); //NOCHECK
    public final PropertyName hbarPolicyName =  new PropertyName("hbarPolicy"); //NOCHECK
    public final PropertyName headerName =  new PropertyName("header"); //NOCHECK
    public final PropertyName headerTextName =  new PropertyName("headerText"); //NOCHECK
    public final PropertyName heightName =  new PropertyName("height"); //NOCHECK
    public final PropertyName hgapName =  new PropertyName("hgap"); //NOCHECK
    public final PropertyName hgrowName =  new PropertyName("hgrow"); //NOCHECK
    public final PropertyName hideOnClickName =  new PropertyName("hideOnClick"); //NOCHECK
    public final PropertyName hideOnEscapeName =  new PropertyName("hideOnEscape"); //NOCHECK
    public final PropertyName hmaxName =  new PropertyName("hmax"); //NOCHECK
    public final PropertyName hminName =  new PropertyName("hmin"); //NOCHECK
    public final PropertyName hvalueName =  new PropertyName("hvalue"); //NOCHECK
    public final PropertyName hGroupName =  new PropertyName("hGroup"); //NOCHECK
    public final PropertyName horizontalGridLinesVisibleName =  new PropertyName("horizontalGridLinesVisible"); //NOCHECK
    public final PropertyName horizontalZeroLineVisibleName =  new PropertyName("horizontalZeroLineVisible"); //NOCHECK
    public final PropertyName htmlTextName =  new PropertyName("htmlText"); //NOCHECK
    
    public final PropertyName iconifiedName = new PropertyName("iconified"); //NOCHECK
    public final PropertyName idName =  new PropertyName("id"); //NOCHECK
    public final PropertyName imageName =  new PropertyName("image"); //NOCHECK
    public final PropertyName indeterminateName =  new PropertyName("indeterminate"); //NOCHECK
    public final PropertyName insetsName =  new PropertyName("insets"); //NOCHECK
    public final PropertyName itemsName =  new PropertyName("items"); //NOCHECK
    public final PropertyName labelName =  new PropertyName("label"); //NOCHECK
    public final PropertyName labelForName =  new PropertyName("labelFor"); //NOCHECK
    public final PropertyName labelFormatterName =  new PropertyName("labelFormatter"); //NOCHECK
    public final PropertyName labelLineLengthName =  new PropertyName("labelLineLength"); //NOCHECK
    public final PropertyName labelPaddingName =  new PropertyName("labelPadding"); //NOCHECK
    public final PropertyName labelsVisibleName =  new PropertyName("labelsVisible"); //NOCHECK
    public final PropertyName largeArcFlagName =  new PropertyName("largeArcFlag"); //NOCHECK
    public final PropertyName layoutBoundsName =  new PropertyName("layoutBounds"); //NOCHECK
    public final PropertyName layoutXName =  new PropertyName("layoutX"); //NOCHECK
    public final PropertyName layoutYName =  new PropertyName("layoutY"); //NOCHECK
    public final PropertyName leftName =  new PropertyName("left"); //NOCHECK
    public final PropertyName legendSideName =  new PropertyName("legendSide"); //NOCHECK
    public final PropertyName legendVisibleName =  new PropertyName("legendVisible"); //NOCHECK
    public final PropertyName lengthName =  new PropertyName("length"); //NOCHECK
    public final PropertyName lightOnName =  new PropertyName("lightOn"); //NOCHECK
    public final PropertyName lineSpacingName =  new PropertyName("lineSpacing"); //NOCHECK
    public final PropertyName lowerBoundName =  new PropertyName("lowerBound"); //NOCHECK
    public final PropertyName majorTickUnitName =  new PropertyName("majorTickUnit"); //NOCHECK
    public final PropertyName materialName =  new PropertyName("material"); //NOCHECK
    public final PropertyName maxName =  new PropertyName("max"); //NOCHECK
    public final PropertyName maxHeightName =  new PropertyName("maxHeight"); //NOCHECK
    public final PropertyName maxPageIndicatorCountName =  new PropertyName("maxPageIndicatorCount"); //NOCHECK
    public final PropertyName maxWidthName =  new PropertyName("maxWidth"); //NOCHECK
    public final PropertyName maximizedName = new PropertyName("maximized"); //NOCHECK
    public final PropertyName menusName =  new PropertyName("menus"); //NOCHECK
    public final PropertyName meshName =  new PropertyName("mesh"); //NOCHECK
    public final PropertyName minName =  new PropertyName("min"); //NOCHECK
    public final PropertyName minHeightName =  new PropertyName("minHeight"); //NOCHECK
    public final PropertyName minorTickCountName =  new PropertyName("minorTickCount"); //NOCHECK
    public final PropertyName minorTickLengthName =  new PropertyName("minorTickLength"); //NOCHECK
    public final PropertyName minorTickVisibleName =  new PropertyName("minorTickVisible"); //NOCHECK
    public final PropertyName minViewportHeightName =  new PropertyName("minViewportHeight"); //NOCHECK
    public final PropertyName minViewportWidthName =  new PropertyName("minViewportWidth"); //NOCHECK
    public final PropertyName minWidthName =  new PropertyName("minWidth"); //NOCHECK
    public final PropertyName mnemonicParsingName =  new PropertyName("mnemonicParsing"); //NOCHECK
    public final PropertyName mouseTransparentName =  new PropertyName("mouseTransparent"); //NOCHECK
    public final PropertyName nearClipName =  new PropertyName("nearClip"); //NOCHECK
    public final PropertyName nodeOrientationName =  new PropertyName("nodeOrientation"); //NOCHECK
    public final PropertyName onActionName =  new PropertyName("onAction"); //NOCHECK
    public final PropertyName onAutoHideName =  new PropertyName("onAutoHide"); //NOCHECK
    public final PropertyName onClosedName =  new PropertyName("onClosed"); //NOCHECK
    public final PropertyName onCloseRequestName =  new PropertyName("onCloseRequest"); //NOCHECK
    public final PropertyName onContextMenuRequestedName =  new PropertyName("onContextMenuRequested"); //NOCHECK
    public final PropertyName onDragDetectedName =  new PropertyName("onDragDetected"); //NOCHECK
    public final PropertyName onDragDoneName =  new PropertyName("onDragDone"); //NOCHECK
    public final PropertyName onDragDroppedName =  new PropertyName("onDragDropped"); //NOCHECK
    public final PropertyName onDragEnteredName =  new PropertyName("onDragEntered"); //NOCHECK
    public final PropertyName onDragExitedName =  new PropertyName("onDragExited"); //NOCHECK
    public final PropertyName onDragOverName =  new PropertyName("onDragOver"); //NOCHECK
    public final PropertyName onEditCancelName =  new PropertyName("onEditCancel"); //NOCHECK
    public final PropertyName onEditCommitName =  new PropertyName("onEditCommit"); //NOCHECK
    public final PropertyName onEditStartName =  new PropertyName("onEditStart"); //NOCHECK
    public final PropertyName onErrorName =  new PropertyName("onError"); //NOCHECK
    public final PropertyName onHiddenName =  new PropertyName("onHidden"); //NOCHECK
    public final PropertyName onHidingName =  new PropertyName("onHiding"); //NOCHECK
    public final PropertyName onInputMethodTextChangedName =  new PropertyName("onInputMethodTextChanged"); //NOCHECK
    public final PropertyName onKeyPressedName =  new PropertyName("onKeyPressed"); //NOCHECK
    public final PropertyName onKeyReleasedName =  new PropertyName("onKeyReleased"); //NOCHECK
    public final PropertyName onKeyTypedName =  new PropertyName("onKeyTyped"); //NOCHECK
    public final PropertyName onMenuValidationName =  new PropertyName("onMenuValidation"); //NOCHECK
    public final PropertyName onMouseClickedName =  new PropertyName("onMouseClicked"); //NOCHECK
    public final PropertyName onMouseDragEnteredName =  new PropertyName("onMouseDragEntered"); //NOCHECK
    public final PropertyName onMouseDragExitedName =  new PropertyName("onMouseDragExited"); //NOCHECK
    public final PropertyName onMouseDraggedName =  new PropertyName("onMouseDragged"); //NOCHECK
    public final PropertyName onMouseDragOverName =  new PropertyName("onMouseDragOver"); //NOCHECK
    public final PropertyName onMouseDragReleasedName =  new PropertyName("onMouseDragReleased"); //NOCHECK
    public final PropertyName onMouseEnteredName =  new PropertyName("onMouseEntered"); //NOCHECK
    public final PropertyName onMouseExitedName =  new PropertyName("onMouseExited"); //NOCHECK
    public final PropertyName onMouseMovedName =  new PropertyName("onMouseMoved"); //NOCHECK
    public final PropertyName onMousePressedName =  new PropertyName("onMousePressed"); //NOCHECK
    public final PropertyName onMouseReleasedName =  new PropertyName("onMouseReleased"); //NOCHECK
    public final PropertyName onPullToRefreshName = new PropertyName("onPullToRefresh"); //NOCHECK
    public final PropertyName onRotateName =  new PropertyName("onRotate"); //NOCHECK
    public final PropertyName onRotationFinishedName =  new PropertyName("onRotationFinished"); //NOCHECK
    public final PropertyName onRotationStartedName =  new PropertyName("onRotationStarted"); //NOCHECK
    public final PropertyName onScrollName =  new PropertyName("onScroll"); //NOCHECK
    public final PropertyName onScrollFinishedName =  new PropertyName("onScrollFinished"); //NOCHECK
    public final PropertyName onScrollStartedName =  new PropertyName("onScrollStarted"); //NOCHECK
    public final PropertyName onScrollToName =  new PropertyName("onScrollTo"); //NOCHECK
    public final PropertyName onScrollToColumnName =  new PropertyName("onScrollToColumn"); //NOCHECK
    public final PropertyName onSelectionChangedName =  new PropertyName("onSelectionChanged"); //NOCHECK
    public final PropertyName onShowingName =  new PropertyName("onShowing"); //NOCHECK
    public final PropertyName onShownName =  new PropertyName("onShown"); //NOCHECK
    public final PropertyName onSortName =  new PropertyName("onSort"); //NOCHECK
    public final PropertyName onSwipeDownName =  new PropertyName("onSwipeDown"); //NOCHECK
    public final PropertyName onSwipeLeftName =  new PropertyName("onSwipeLeft"); //NOCHECK
    public final PropertyName onSwipeRightName =  new PropertyName("onSwipeRight"); //NOCHECK
    public final PropertyName onSwipeUpName =  new PropertyName("onSwipeUp"); //NOCHECK
    public final PropertyName onTouchMovedName =  new PropertyName("onTouchMoved"); //NOCHECK
    public final PropertyName onTouchPressedName =  new PropertyName("onTouchPressed"); //NOCHECK
    public final PropertyName onTouchReleasedName =  new PropertyName("onTouchReleased"); //NOCHECK
    public final PropertyName onTouchStationaryName =  new PropertyName("onTouchStationary"); //NOCHECK
    public final PropertyName onZoomName =  new PropertyName("onZoom"); //NOCHECK
    public final PropertyName onZoomFinishedName =  new PropertyName("onZoomFinished"); //NOCHECK
    public final PropertyName onZoomStartedName =  new PropertyName("onZoomStarted"); //NOCHECK
    public final PropertyName opacityName =  new PropertyName("opacity"); //NOCHECK
    public final PropertyName opaqueInsetsName =  new PropertyName("opaqueInsets"); //NOCHECK
    public final PropertyName optionsName = new PropertyName("options"); //NOCHECK
    public final PropertyName orientationName =  new PropertyName("orientation"); //NOCHECK
    public final PropertyName paddingName =  new PropertyName("padding"); //NOCHECK
    public final PropertyName pageCountName =  new PropertyName("pageCount"); //NOCHECK
    public final PropertyName panesName =  new PropertyName("panes"); //NOCHECK
    public final PropertyName pannableName =  new PropertyName("pannable"); //NOCHECK
    public final PropertyName percentHeightName =  new PropertyName("percentHeight"); //NOCHECK
    public final PropertyName percentWidthName =  new PropertyName("percentWidth"); //NOCHECK
    public final PropertyName pickOnBoundsName =  new PropertyName("pickOnBounds"); //NOCHECK
    public final PropertyName placeholderName =  new PropertyName("placeholder"); //NOCHECK
    public final PropertyName pointsName =  new PropertyName("points"); //NOCHECK
    public final PropertyName popupSideName =  new PropertyName("popupSide"); //NOCHECK
    public final PropertyName prefColumnCountName =  new PropertyName("prefColumnCount"); //NOCHECK
    public final PropertyName prefColumnsName =  new PropertyName("prefColumns"); //NOCHECK
    public final PropertyName prefHeightName =  new PropertyName("prefHeight"); //NOCHECK
    public final PropertyName prefRowCountName =  new PropertyName("prefRowCount"); //NOCHECK
    public final PropertyName prefRowsName =  new PropertyName("prefRows"); //NOCHECK
    public final PropertyName prefTileHeightName =  new PropertyName("prefTileHeight"); //NOCHECK
    public final PropertyName prefTileWidthName =  new PropertyName("prefTileWidth"); //NOCHECK
    public final PropertyName prefViewportHeightName =  new PropertyName("prefViewportHeight"); //NOCHECK
    public final PropertyName prefViewportWidthName =  new PropertyName("prefViewportWidth"); //NOCHECK
    public final PropertyName prefWidthName =  new PropertyName("prefWidth"); //NOCHECK
    public final PropertyName prefWrapLengthName =  new PropertyName("prefWrapLength"); //NOCHECK
    public final PropertyName preserveRatioName =  new PropertyName("preserveRatio"); //NOCHECK
    public final PropertyName progressName =  new PropertyName("progress"); //NOCHECK
    public final PropertyName promptTextName =  new PropertyName("promptText"); //NOCHECK
    public final PropertyName radiusName =  new PropertyName("radius"); //NOCHECK
    public final PropertyName radiusXName =  new PropertyName("radiusX"); //NOCHECK
    public final PropertyName radiusYName =  new PropertyName("radiusY"); //NOCHECK
    public final PropertyName resizableName =  new PropertyName("resizable"); //NOCHECK
    public final PropertyName rightName =  new PropertyName("right"); //NOCHECK
    public final PropertyName rootName = new PropertyName("root"); //NOCHECK
    public final PropertyName rotateName =  new PropertyName("rotate"); //NOCHECK
    public final PropertyName rotateGraphicName =  new PropertyName("rotateGraphic"); //NOCHECK
    public final PropertyName rotationAxisName =  new PropertyName("rotationAxis"); //NOCHECK
    public final PropertyName rowConstraintsName =  new PropertyName("rowConstraints"); //NOCHECK
    public final PropertyName rowValignmentName =  new PropertyName("rowValignment"); //NOCHECK
    public final PropertyName scaleName =  new PropertyName("scale"); //NOCHECK
    public final PropertyName scaleShapeName =  new PropertyName("scaleShape"); //NOCHECK
    public final PropertyName scaleXName =  new PropertyName("scaleX"); //NOCHECK
    public final PropertyName scaleYName =  new PropertyName("scaleY"); //NOCHECK
    public final PropertyName scaleZName =  new PropertyName("scaleZ"); //NOCHECK
    public final PropertyName sceneName = new PropertyName("scene"); //NOCHECK
    public final PropertyName scopeName =  new PropertyName("scope"); //NOCHECK
    public final PropertyName scrollLeftName =  new PropertyName("scrollLeft"); //NOCHECK
    public final PropertyName scrollTopName =  new PropertyName("scrollTop"); //NOCHECK
    public final PropertyName searchBoxVisibleName = new PropertyName("searchBoxVisible"); //NOCHECK
    public final PropertyName selectedName =  new PropertyName("selected"); //NOCHECK
    public final PropertyName selectionTypeName = new PropertyName("selectionType"); //NOCHECK
    public final PropertyName shapeName = new PropertyName("shape"); //NOCHECK
    public final PropertyName showRootName =  new PropertyName("showRoot"); //NOCHECK
    public final PropertyName showTickLabelsName =  new PropertyName("showTickLabels"); //NOCHECK
    public final PropertyName showTickMarksName =  new PropertyName("showTickMarks"); //NOCHECK
    public final PropertyName showWeekNumbersName =  new PropertyName("showWeekNumbers"); //NOCHECK
    public final PropertyName sideName =  new PropertyName("side"); //NOCHECK
    public final PropertyName smoothName =  new PropertyName("smooth"); //NOCHECK
    public final PropertyName snapToPixelName =  new PropertyName("snapToPixel"); //NOCHECK
    public final PropertyName snapToTicksName =  new PropertyName("snapToTicks"); //NOCHECK
    public final PropertyName sortableName =  new PropertyName("sortable"); //NOCHECK
    public final PropertyName sortModeName =  new PropertyName("sortMode"); //NOCHECK
    public final PropertyName sortNodeName =  new PropertyName("sortNode"); //NOCHECK
    public final PropertyName sortOrderName =  new PropertyName("sortOrder"); //NOCHECK
    public final PropertyName sortTypeName =  new PropertyName("sortType"); //NOCHECK
    public final PropertyName spacingName =  new PropertyName("spacing"); //NOCHECK
    public final PropertyName startAngleName =  new PropertyName("startAngle"); //NOCHECK
    public final PropertyName startMarginName =  new PropertyName("startMargin"); //NOCHECK
    public final PropertyName startXName =  new PropertyName("startX"); //NOCHECK
    public final PropertyName startYName =  new PropertyName("startY"); //NOCHECK
    public final PropertyName strikethroughName =  new PropertyName("strikethrough"); //NOCHECK
    public final PropertyName strokeName =  new PropertyName("stroke"); //NOCHECK
    public final PropertyName strokeDashOffsetName =  new PropertyName("strokeDashOffset"); //NOCHECK
    public final PropertyName strokeLineCapName =  new PropertyName("strokeLineCap"); //NOCHECK
    public final PropertyName strokeLineJoinName =  new PropertyName("strokeLineJoin"); //NOCHECK
    public final PropertyName strokeMiterLimitName =  new PropertyName("strokeMiterLimit"); //NOCHECK
    public final PropertyName strokeTypeName =  new PropertyName("strokeType"); //NOCHECK
    public final PropertyName strokeWidthName =  new PropertyName("strokeWidth"); //NOCHECK
    public final PropertyName styleName =  new PropertyName("style"); //NOCHECK
    public final PropertyName styleClassName =  new PropertyName("styleClass"); //NOCHECK
    public final PropertyName stylesheetsName =  new PropertyName("stylesheets"); //NOCHECK
    public final PropertyName sweepFlagName =  new PropertyName("sweepFlag"); //NOCHECK
    public final PropertyName tabClosingPolicyName =  new PropertyName("tabClosingPolicy"); //NOCHECK
    public final PropertyName tableMenuButtonVisibleName =  new PropertyName("tableMenuButtonVisible"); //NOCHECK
    public final PropertyName tabMaxHeightName =  new PropertyName("tabMaxHeight"); //NOCHECK
    public final PropertyName tabMaxWidthName =  new PropertyName("tabMaxWidth"); //NOCHECK
    public final PropertyName tabMinHeightName =  new PropertyName("tabMinHeight"); //NOCHECK
    public final PropertyName tabMinWidthName =  new PropertyName("tabMinWidth"); //NOCHECK
    public final PropertyName tabsName =  new PropertyName("tabs"); //NOCHECK
    public final PropertyName textName =  new PropertyName("text"); //NOCHECK
    public final PropertyName textAlignmentName =  new PropertyName("textAlignment"); //NOCHECK
    public final PropertyName textFillName =  new PropertyName("textFill"); //NOCHECK
    public final PropertyName textFormatterName =  new PropertyName("textFormatter"); //NOCHECK
    public final PropertyName textOriginName =  new PropertyName("textOrigin"); //NOCHECK
    public final PropertyName textOverrunName =  new PropertyName("textOverrun"); //NOCHECK
    public final PropertyName tickLabelFillName =  new PropertyName("tickLabelFill"); //NOCHECK
    public final PropertyName tickLabelFontName =  new PropertyName("tickLabelFont"); //NOCHECK
    public final PropertyName tickLabelFormatterName =  new PropertyName("tickLabelFormatter"); //NOCHECK
    public final PropertyName tickLabelGapName =  new PropertyName("tickLabelGap"); //NOCHECK
    public final PropertyName tickLabelRotationName =  new PropertyName("tickLabelRotation"); //NOCHECK
    public final PropertyName tickLabelsVisibleName =  new PropertyName("tickLabelsVisible"); //NOCHECK
    public final PropertyName tickLengthName =  new PropertyName("tickLength"); //NOCHECK
    public final PropertyName tickMarksName =  new PropertyName("tickMarks"); //NOCHECK
    public final PropertyName tickMarkVisibleName =  new PropertyName("tickMarkVisible"); //NOCHECK
    public final PropertyName tickUnitName =  new PropertyName("tickUnit"); //NOCHECK
    public final PropertyName tileAlignmentName =  new PropertyName("tileAlignment"); //NOCHECK
    public final PropertyName tileHeightName =  new PropertyName("tileHeight"); //NOCHECK
    public final PropertyName tileWidthName =  new PropertyName("tileWidth"); //NOCHECK
    public final PropertyName titleFilterName = new PropertyName("titleFilter"); //NOCHECK
    public final PropertyName titleName =  new PropertyName("title"); //NOCHECK
    public final PropertyName titleNodesName = new PropertyName("titleNodes"); //NOCHECK
    public final PropertyName titleSideName = new PropertyName("titleSide"); //NOCHECK
    public final PropertyName toggleGroupName =  new PropertyName("toggleGroup"); //NOCHECK
    public final PropertyName togglesName = new PropertyName("toggles"); //NOCHECK
    public final PropertyName tooltipName = new PropertyName("tooltip"); //NOCHECK
    public final PropertyName topName =  new PropertyName("top"); //NOCHECK
    public final PropertyName translateXName =  new PropertyName("translateX"); //NOCHECK
    public final PropertyName translateYName =  new PropertyName("translateY"); //NOCHECK
    public final PropertyName translateZName =  new PropertyName("translateZ"); //NOCHECK
    public final PropertyName treeColumnName =  new PropertyName("treeColumn"); //NOCHECK
    public final PropertyName typeName =  new PropertyName("type"); //NOCHECK
    public final PropertyName underlineName =  new PropertyName("underline"); //NOCHECK
    public final PropertyName unitIncrementName =  new PropertyName("unitIncrement"); //NOCHECK
    public final PropertyName upperBoundName =  new PropertyName("upperBound"); //NOCHECK
    public final PropertyName userAgentStylesheetName =  new PropertyName("userAgentStylesheet"); //NOCHECK
    public final PropertyName valignmentName =  new PropertyName("valignment"); //NOCHECK
    public final PropertyName valueName =  new PropertyName("value"); //NOCHECK
    public final PropertyName vbarPolicyName =  new PropertyName("vbarPolicy"); //NOCHECK
    public final PropertyName verticalFieldOfViewName =  new PropertyName("verticalFieldOfView"); //NOCHECK
    public final PropertyName verticalGridLinesVisibleName =  new PropertyName("verticalGridLinesVisible"); //NOCHECK
    public final PropertyName verticalZeroLineVisibleName =  new PropertyName("verticalZeroLineVisible"); //NOCHECK
    public final PropertyName vgapName =  new PropertyName("vgap"); //NOCHECK
    public final PropertyName vgrowName =  new PropertyName("vgrow"); //NOCHECK
    public final PropertyName viewportName =  new PropertyName("viewport"); //NOCHECK
    public final PropertyName viewportBoundsName =  new PropertyName("viewportBounds"); //NOCHECK
    public final PropertyName visibleName =  new PropertyName("visible"); //NOCHECK
    public final PropertyName visibleAmountName =  new PropertyName("visibleAmount"); //NOCHECK
    public final PropertyName visibleRowCountName =  new PropertyName("visibleRowCount"); //NOCHECK
    public final PropertyName visitedName =  new PropertyName("visited"); //NOCHECK
    public final PropertyName vmaxName =  new PropertyName("vmax"); //NOCHECK
    public final PropertyName vminName =  new PropertyName("vmin"); //NOCHECK
    public final PropertyName vvalueName =  new PropertyName("vvalue"); //NOCHECK
    public final PropertyName vGroupName =  new PropertyName("vGroup"); //NOCHECK
    public final PropertyName widthName =  new PropertyName("width"); //NOCHECK
    public final PropertyName wrappingWidthName =  new PropertyName("wrappingWidth"); //NOCHECK
    public final PropertyName wrapTextName =  new PropertyName("wrapText"); //NOCHECK
    public final PropertyName xName =  new PropertyName("x"); //NOCHECK
    public final PropertyName xAxisName = new PropertyName("xAxis"); //NOCHECK
    public final PropertyName XAxisRotationName =  new PropertyName("XAxisRotation"); //NOCHECK
    public final PropertyName yName =  new PropertyName("y"); //NOCHECK
    public final PropertyName yAxisName = new PropertyName("yAxis"); //NOCHECK
    public final PropertyName zeroPositionName =  new PropertyName("zeroPosition"); //NOCHECK
    public final PropertyName zoomName =  new PropertyName("zoom"); //NOCHECK
    public final PropertyName SplitPane_resizableWithParentName =  new PropertyName("resizableWithParent", javafx.scene.control.SplitPane.class); //NOCHECK
    public final PropertyName AnchorPane_bottomAnchorName =  new PropertyName("bottomAnchor", javafx.scene.layout.AnchorPane.class); //NOCHECK
    public final PropertyName AnchorPane_leftAnchorName =  new PropertyName("leftAnchor", javafx.scene.layout.AnchorPane.class); //NOCHECK
    public final PropertyName AnchorPane_rightAnchorName =  new PropertyName("rightAnchor", javafx.scene.layout.AnchorPane.class); //NOCHECK
    public final PropertyName AnchorPane_topAnchorName =  new PropertyName("topAnchor", javafx.scene.layout.AnchorPane.class); //NOCHECK
    public final PropertyName AnchorPane_anchorsGroupName =  new PropertyName("anchorsGroup", javafx.scene.layout.AnchorPane.class); //NOCHECK
    public final PropertyName BorderPane_alignmentName =  new PropertyName("alignment", javafx.scene.layout.BorderPane.class); //NOCHECK
    public final PropertyName BorderPane_marginName =  new PropertyName("margin", javafx.scene.layout.BorderPane.class); //NOCHECK
    public final PropertyName FlowPane_marginName =  new PropertyName("margin", javafx.scene.layout.FlowPane.class); //NOCHECK
    public final PropertyName GridPane_columnIndexName =  new PropertyName("columnIndex", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_columnSpanName =  new PropertyName("columnSpan", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_halignmentName =  new PropertyName("halignment", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_hgrowName =  new PropertyName("hgrow", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_marginName =  new PropertyName("margin", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_rowIndexName =  new PropertyName("rowIndex", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_rowSpanName =  new PropertyName("rowSpan", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_valignmentName =  new PropertyName("valignment", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName GridPane_vgrowName =  new PropertyName("vgrow", javafx.scene.layout.GridPane.class); //NOCHECK
    public final PropertyName HBox_hgrowName =  new PropertyName("hgrow", javafx.scene.layout.HBox.class); //NOCHECK
    public final PropertyName HBox_marginName =  new PropertyName("margin", javafx.scene.layout.HBox.class); //NOCHECK
    public final PropertyName StackPane_alignmentName =  new PropertyName("alignment", javafx.scene.layout.StackPane.class); //NOCHECK
    public final PropertyName StackPane_marginName =  new PropertyName("margin", javafx.scene.layout.StackPane.class); //NOCHECK
    public final PropertyName TilePane_alignmentName =  new PropertyName("alignment", javafx.scene.layout.TilePane.class); //NOCHECK
    public final PropertyName TilePane_marginName =  new PropertyName("margin", javafx.scene.layout.TilePane.class); //NOCHECK
    public final PropertyName VBox_marginName =  new PropertyName("margin", javafx.scene.layout.VBox.class); //NOCHECK
    public final PropertyName VBox_vgrowName =  new PropertyName("vgrow", javafx.scene.layout.VBox.class); //NOCHECK
    public final PropertyName source = new PropertyName("source"); //NOCHECK


}
