<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>scenebuilder.ext.source.gen</artifactId>

    <parent>
        <groupId>com.gluonhq.jfxapps</groupId>
        <artifactId>scenebuilder.ext</artifactId>
        <version>${scenebuilder.version}</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>scenebuilder.api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>scenebuilder.app.starter</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>scenebuilder.app.starter.test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>resolve-jar-path</id>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.treilhes.jfxplace</groupId>
                        <artifactId>javafx.graphics.patch</artifactId>
                        <version>${jfxplace.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.treilhes.jfxplace</groupId>
                        <artifactId>javafx.fxml.patch</artifactId>
                        <version>${jfxplace.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <useModulePath>true</useModulePath>
                    <compilerArgs>
                        <arg>--patch-module</arg>
                        <arg>javafx.fxml=${com.treilhes.jfxplace:javafx.fxml.patch:jar}</arg>
                        <arg>--patch-module</arg>
                        <arg>javafx.graphics=${com.treilhes.jfxplace:javafx.graphics.patch:jar}</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useModulePath>true</useModulePath>
                    <argLine>
                        --add-opens javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
                        --patch-module javafx.graphics=${com.treilhes.jfxplace:javafx.graphics.patch:jar}
                        --patch-module javafx.fxml=${com.treilhes.jfxplace:javafx.fxml.patch:jar}
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>