module scenebuilder.starter {

    requires transitive aether.api;
    requires transitive aether.connector.basic;
    requires transitive aether.impl;
    requires transitive aether.spi;
    requires transitive aether.transport.file;
    requires transitive aether.transport.http;
    requires transitive aether.util;
    requires transitive com.fasterxml.jackson.annotation;
    requires transitive com.fasterxml.jackson.core;
    requires transitive com.fasterxml.jackson.databind;
    requires transitive commons.codec;
    requires transitive httpclient;
    requires transitive httpcore;
    requires transitive io.reactivex.rxjava2;
    requires transitive java.desktop;
    requires transitive java.logging;
    requires transitive java.prefs;
    requires transitive java.xml;
    requires transitive javafx.base;
    requires transitive javafx.controls;
    requires transitive javafx.fxml;
    requires transitive javafx.graphics;
    requires transitive javafx.media;
    requires transitive javafx.swing;
    requires transitive javafx.web;
    requires transitive javax.json.api;
    requires transitive logback.classic;
    requires transitive logback.core;
    requires transitive maven.aether.provider;
    requires transitive org.apache.commons.lang3;
    requires transitive org.reactivestreams;
    requires transitive org.slf4j;
    requires transitive plexus.utils;
    requires transitive rxjavafx;
    requires transitive spring.aop;
    requires transitive spring.beans;
    requires transitive spring.boot;
    requires transitive spring.context;
    requires transitive spring.core;

}