jfxapps:
  registry:
    snapshotsAllowed: true
#    defaults:
#      jira:
#        groupId: com.gluonhq.jfxapps
#        artifactId: manager.registry
#        mandatory: true

  maven:
    directory: ${user.home}/.m2/repository
#    redirectionsEnabled: true
#    redirect:
#      - groupId: com.gluonhq.jfxapps
#        artifactId: jfxapps.core.api
#        path: ../../jfxapps.core/jfxapps.core.api/target/classes

server:
  port: 8080

spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true

springdoc:
  show-actuator: true