<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.gluonhq.jfxapps</groupId>
		<artifactId>jfxapps.delivery</artifactId>
		<version>${jfxapps.version}</version>
	</parent>
	<artifactId>jfxapps.delivery.package</artifactId>
	<packaging>pom</packaging>

	<properties>
	    <!-- Replace SNAPSHOT with .0 to keep numeric MSI version -->
	    <app.version>${project.version.replace("-SNAPSHOT", ".0")}</app.version>
	    <app.name>JfxAppsBoot</app.name>
	    <app.description>JfxApps Boot application</app.description>
	    <app.vendor>Gluon</app.vendor>
	    <main.module.name>jfxapps.boot.main</main.module.name>
	    <main.class.name>com.gluonhq.jfxapps.boot.main.Main</main.class.name>
        
        
        <!-- For about.properties file -->
        <buildDate>${maven.build.timestamp}</buildDate>
        <buildDateFormat>${maven.build.timestamp.format}</buildDateFormat>
        <javaVersion>${java.version}, ${java.runtime.name}</javaVersion>
        <javafxVersion>${javafx.version}</javafxVersion>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss</maven.build.timestamp.format>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.gluonhq.jfxapps</groupId>
			<artifactId>jfxapps.boot.main</artifactId>
			<version>${jfxapps.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>com.gluonhq.jfxapps</groupId>
				<artifactId>emc4j-maven-plugin</artifactId>
				<version>${jfxapps.version}</version>
				<configuration>
					<emc4jVersion>${jfxapps.version}</emc4jVersion>
				</configuration>
				<executions>
					<execution>
						<id>run</id>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<debug>false</debug>
							<profile>jira</profile>
							<profileFile>${basedir}/src/main/resources/application-jira.yaml</profileFile>
							<applicationId>f207e2cf-2df1-4504-bacd-1abed4212d48</applicationId>
							<javaOptions>
								<javaOption>-Dnexus.password=${nexus.password}</javaOption>
								<!--
								<javaOption>-Dlogging.level.org.springframework.beans.factory.support=DEBUG</javaOption>
								<javaOption>-Dlogging.level.org.springframework.beans.factory=DEBUG</javaOption>
								<javaOption>-Dlogging.level.org.springframework.context.annotation=DEBUG</javaOption>
						      -->
		
							</javaOptions>
						</configuration>
					</execution>
					<execution>
						<id>package</id>
						<goals>
							<goal>package</goal>
						</goals>
						<configuration>
							<profile>jira</profile>
							<profileFile>${basedir}/src/main/resources/application-jira.yaml</profileFile>
							
							<!-- parameter for jpackage plugin-->
							<toolhome>${java.home}</toolhome>
							<appversion>${app.version}</appversion>
							<input>${project.build.directory}/application</input>
							<licensefile>${basedir}/src/assets/LICENSE.txt</licensefile>
							<module>${main.module.name}/${main.class.name}</module>
							<name>${app.name}</name>
							<description>${app.description}</description>
							<vendor>${app.vendor}</vendor>
							<verbose>true</verbose>
							<runtimeimage>${project.build.directory}/runtime</runtimeimage>
							<dest>${project.build.directory}/package</dest>
							<!-- <type>PLATFORM</type> -->
							<javaoptions>-Djavafx.allowjs=true</javaoptions>
							<javaoptions>--add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED</javaoptions>
							<javaoptions>--enable-native-access=javafx.graphics</javaoptions>
							<javaoptions>--sun-misc-unsafe-memory-access=allow</javaoptions>
							<javaoptions>-Djava.library.path=runtime\bin;runtime\lib</javaoptions>
							<icon>${basedir}/src/assets/windows/icon-windows.ico</icon>

							<!-- Windows -->
							<windirchooser>true</windirchooser>
							<winmenu>true</winmenu>
							<winmenugroup>Scene Builder</winmenugroup>
							<winperuserinstall>true</winperuserinstall>
							<winshortcut>true</winshortcut>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>