<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.treilhes.scenebuilder</groupId>
        <artifactId>scenebuilder-parent</artifactId>
        <version>${scenebuilder.version}</version>
    </parent>
    <groupId>com.gluonhq.jfxapps</groupId>
    <artifactId>jfxapps.metadata</artifactId>
    <packaging>pom</packaging>
    
    <properties>
    	<jackson-dataformat-properties.version>2.20.1</jackson-dataformat-properties.version>
        <byte-buddy.version>1.18.1</byte-buddy.version>
        <slf4j.version>2.0.17</slf4j.version>
        <commons-configuration2.version>2.10.1</commons-configuration2.version>
        <freemarker.version>2.3.34</freemarker.version>
        <javafx.version>11</javafx.version>
        <logback.version>1.5.3</logback.version>
    </properties>

    <modules>
        <module>jfxapps.metadata.generator</module>
        <module>jfxapps.metadata-maven-plugin</module>
        <module>scenebuilder-source-override-maven-plugin</module>
    </modules>
</project>