<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gluonhq.jfxapps</groupId>
        <artifactId>scenebuilder</artifactId>
        <version>${scenebuilder.version}</version>
    </parent>
    <artifactId>scenebuilder.launcher</artifactId>

    <properties>
        <clean>true</clean>
        <debug>false</debug>
    </properties>
    
    <!--TIPS: adding dependencies here allow eclipse to find sources for the debugger -->
    <dependencies>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>scenebuilder.api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.gluonhq.jfxapps</groupId>
            <artifactId>scenebuilder.starter</artifactId>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.treilhes.jfxplace</groupId>
            <artifactId>jfxplace.core.appmngr</artifactId>
            <version>${jfxplace.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.jfxplace</groupId>
                <artifactId>jfxplace-maven-plugin</artifactId>
                <version>${jfxplace.version}</version>
                <configuration>
                    <jfxplaceVersion>${jfxplace.version}</jfxplaceVersion>
                    <clean>${clean}</clean>
                    <debug>${debug}</debug>
                    <profiles>
                        <profile>devlookup,scenebuilder</profile>
                    </profiles>
                    <applicationId>06ae1f67-a8aa-49e3-abb5-4f108534578c</applicationId>
                    <registry>
                        <groupId>com.gluonhq.jfxapps</groupId>
                        <artifactId>scenebuilder.registry</artifactId>
                        <version>${scenebuilder.version}</version>
                    </registry>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    
    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.treilhes.jfxplace</groupId>
                        <artifactId>jfxplace-maven-plugin</artifactId>
                        <version>${jfxplace.version}</version>
                        <configuration>
                            <jfxplaceVersion>${jfxplace.version}</jfxplaceVersion>
                            <clean>${clean}</clean>
                            <debug>${debug}</debug>
                            <profiles>
                                <profile>devlookup,scenebuilder</profile>
                            </profiles>
                            <applicationId>06ae1f67-a8aa-49e3-abb5-4f108534578c</applicationId>
                            <registry>
                                <groupId>com.gluonhq.jfxapps</groupId>
                                <artifactId>scenebuilder.registry</artifactId>
                                <version>${scenebuilder.version}</version>
                                <localFolder>${basedir}/src/main/resources/registry</localFolder>
                            </registry>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>